/*
 * This source file was generated by the Gradle 'init' task
 */

package org.sepp;

import org.apache.commons.cli.*;

public class Cli {

  private static Cli INSTANCE = null;

  public CommandLineParser parser;
  public Options options;
  public HelpFormatter hFormatter;

  public static synchronized Cli getInstance() {
    if (INSTANCE == null) {
      INSTANCE = new Cli();
    }
    return INSTANCE;
  }

  public Cli() {
    this.parser = new DefaultParser();
    this.options = new Options();
    this.options.addOption("h", "help", false, "Prints this message");
    this.options.addOption("v", "test", false, "this is a test");
    this.options.addOption("t", "title", true, "Set title of configuration");
    this.options.addOption("r", "run", true, "Directory to run in");
    this.options.addOption(
        Option.builder("a")
            .longOpt("add-task")
            .hasArgs()
            .numberOfArgs(3)
            .desc(
                "Task to add <name> <type> <path-to-shell-script>. Shell script path is not store,"
                    + " only the contents of the file")
            .build());
    this.options.addOption("l", "load", true, "Configuration to load");
    this.options.addOption("c", "create", false, "Create configuration");
    this.options.addOption(
        Option.builder("d")
            .longOpt("diff")
            .numberOfArgs(2)
            .desc("Diff two files <skeleton-path> <submission-path>")
            .build());
    this.hFormatter = new HelpFormatter();
  }

  public CommandLine parse(String[] args) throws ParseException {
    return this.parser.parse(this.options, args);
  }

  public void printHelp() {
    hFormatter.printHelp("utility-name", options);
  }
}
