/*
 * This source file was generated by the Gradle 'init' task
 */

package org.sepp;

import java.io.File;

import org.apache.commons.cli.*;

public class Cli {

  public static void main(String[] args) {
    CommandLineParser parser = new DefaultParser();

    Options options = new Options();
    options.addOption("h", "help", false, "print this message");
    options.addOption("v", "test", false, "this is a test");
    options.addOption("f", "file", true, "file to process");
    options.addOption("l", "load", true, "config to load");

    try {
      CommandLine line = parser.parse(options, args);

      if (line.hasOption("help")) {
        HelpFormatter formatter = new HelpFormatter();
        formatter.printHelp("utility-name", options);
      }

      if (line.hasOption("test")) {
        System.out.println("The test works");
      }

      if (line.hasOption("file")) {
        System.out.println("File to process: " + line.getOptionValue("file"));
      }

      if (line.hasOption("load")){
        
        File configFile = new File(line.getOptionValue("load"));
        Config config = Config.LoadFromFile(configFile);
      }
    } catch (ParseException exp) {
      System.err.println("Parsing failed.  Reason: " + exp.getMessage());
    }
  }
}
