/*
 * This source file was generated by the Gradle 'init' task
 */
package org.sepp;

import org.junit.Test;

public class AppTest {
  @Test
  public void appHasAGreeting() {
    App classUnderTest = new App();
  }

  /* @Test
  public void DiffTest() {
    throw new RuntimeException("Not implemented");
  } */
}
