/*
 * This source file was generated by the Gradle 'init' task
 */
package org.sepp;

import static org.junit.Assert.*;

import org.junit.Test;

public class AppTest {
  @Test
  public void appHasAGreeting() {
    App classUnderTest = new App();
  }
}
